name: Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy Node.js app
      uses: jjst/action-digitalocean-deploy-app@v2
      with:
        app_name: ClassCriticApp
        key: ${{secrets.SSH_KEY}}
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
