name: Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy Node.js app
      uses: jjst/action-digitalocean-deploy-app@v2
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{ secrets.SSH_USERNAME }}
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        app-id: "ClassCriticApp"

        scripts: |
          mkdir deployment
          cd deployment
          git clone https://github.com/agiledev-students-fall2022/final-project-team-rotten-classes.git
          echo 'Deployment successful to Digital Ocean'
