name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy Node.js app
      uses: jjst/action-digitalocean-deploy-app@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        app-id: "ClassCriticApp"
